# Niri compositor environment
EDITOR=fresh
VISUAL=fresh
QT_QPA_PLATFORMTHEME=qt6ct

# Graphics (AMD CPU + NVIDIA dGPU)
AMD_VULKAN_ICD=RADV
GTK_USE_PORTAL=1

# Thunderbird (Mozilla)
MOZ_ENABLE_WAYLAND=1

# Electron apps
ELECTRON_OZONE_PLATFORM_HINT=wayland
